### PR TITLE
Embed base64-encoded iA fonts in stylesheet

### PR DESCRIPTION
**Pull request by evnm**
## Problem
I'd like to use obsidian_ia with the Obsidian iOS app, but the iA Writer typefaces aren't easily installed on mobile devices.

## Solution
I asked about this in the Obsidian Discord and got [a helpful reply](https://discord.com/channels/686053708261228577/817515900349448202/859216071088668673) that led me to this solution.

This change adds base64-encoded iA Writer Quattro V and Mono V typefaces to the stylesheet. The theme will be more self-contained, and thus easier to use on machines that don't have the iA fonts installed. And, critically, it should make the theme usable in the Obsidian mobile app.

### How did I test this?

I copied the updated `obsidian.css` to `.obsidian/themes/obsidian_ia.css` in my vault and my notes render in full iA glory.

To sanity check that it wasn't pulling in my system Quattro font, I renamed all instances of "iA Writer Quattro V" to "iA Writer Quattro H" in the stylesheet, re-copied it into my vault, and the fonts still worked.

### Procedure to create base64'd fonts

1. Download the Quattro and Mono variable TTFs from https://github.com/iaolo/iA-Fonts
2. Upload all four fonts to https://transfonter.org
3. Enable "Base64 encode"
4. Convert and download @font-face kit
5. Copy the contents of the downloaded kit's stylesheet.css to obsidian.css

### CODE REVIEW

**Review by rcvd — APPROVED** [review]

**Comment by evnm** [comment]
@rcvd Are you comfortable merging this? Any more testing I can do?

**Comment by rcvd** [comment]
Sorry, I thought I already did that. Thanks for the reminder.

**Comment by rcvd** [comment]
Not sure if this really works - have to dig a bit deeper. A quick look shows that it doesn't seem to work on iOS but don't know why. Anyway - updating this theme is long overdue.

**Comment by evnm** [comment]
Dang. Not working for me on iOS, either. One way to test the base64'd font technique could be to stuff it into a CSS snippet. This would let us iterate on it without having to update the theme.

**Pull request merged**
